/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/book.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/book.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BackCover.geometry} material={materials['default']} />
      <mesh geometry={nodes.FrontCover.geometry} material={materials['default']} />
      <mesh geometry={nodes.Spine.geometry} material={materials['default']} />
      <mesh geometry={nodes.PagesTop.geometry} material={materials['default']} />
      <mesh geometry={nodes.PagesBottom.geometry} material={materials['default']} />
      <mesh geometry={nodes.MarbleFrame.geometry} material={materials['default']} />
      <mesh geometry={nodes.MarbleFrame_1.geometry} material={materials['default']} />
    </group>
  )
}

useGLTF.preload('/book.glb')
